spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
      database: fitnessactivity

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${server.port}

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

# Custom RabbitMQ properties
rabbitmq.queue.name: activity.queue
rabbitmq.exchange.name: fitness.exchange
rabbitmq.routing.key: activity.tracking

